import type { Snapshot } from "@/lib/types";

export const SAMPLE_NOW = 1_785_833_730;

export const sampleSnapshot = {
  schema_version: 4,
  complete: false,
  scope: { kind: "machine" },
  self: {
    client: "codex",
    session_id: "019fcbf9-d75c-7ba3-a481-18068ea954eb",
  },
  providers: [
    {
      client: "codex",
      ok: true,
      source: "hook-ledger",
      enabled: true,
      dropped: 0,
      error: null,
    },
    {
      client: "claude",
      ok: true,
      source: "claude-agents-json",
      enabled: true,
      dropped: 1,
      error: null,
    },
  ],
  sessions: [
    {
      client: "claude",
      session_id: "7ca88f40-3aed-4f2d-be71-a80e544dd332",
      cwd: "/Users/prb/projects/ai-coord",
      repo_root: "/Users/prb/projects/ai-coord",
      state: "working",
      callsign: "👩‍💻 Baroness Byte",
      name: "live-coordination-dashboard",
      waiting_for: null,
      pid: 32548,
      source: "observer",
      started_at: 1_785_832_480,
      last_seen: 1_785_833_725,
    },
    {
      client: "codex",
      session_id: "019fcbf9-d75c-7ba3-a481-18068ea954eb",
      cwd: "/Users/prb/projects/ai-coord/dashboard",
      repo_root: "/Users/prb/projects/ai-coord",
      state: "working",
      callsign: "🦊 Patch Fox",
      name: null,
      waiting_for: null,
      pid: 64058,
      source: "hook",
      started_at: 1_785_833_578,
      last_seen: 1_785_833_718,
    },
    {
      client: "codex",
      session_id: "019fcbf9-2db4-7be1-90ed-7ba4a7527a84",
      cwd: "/Users/prb/projects/ai-coord",
      repo_root: "/Users/prb/projects/ai-coord",
      state: "waiting",
      callsign: "🐢 Queue Kid",
      name: null,
      waiting_for: null,
      pid: 62706,
      source: "hook",
      started_at: 1_785_833_535,
      last_seen: 1_785_833_400,
    },
    {
      client: "codex",
      session_id: "019fcbf1-1a53-7e20-a682-520d66c5b87f",
      cwd: "/Users/prb/projects/ai-coord",
      repo_root: "/Users/prb/projects/ai-coord",
      state: "waiting",
      callsign: null,
      name: null,
      waiting_for: null,
      pid: 49938,
      source: "hook",
      started_at: 1_785_833_052,
      last_seen: 1_785_833_060,
    },
    {
      client: "codex",
      session_id: "019fcbc9-fc31-7772-9bc9-1c7af36775f5",
      cwd: "/Users/prb/projects/agent-skills",
      repo_root: "/Users/prb/projects/agent-skills",
      state: "idle",
      callsign: "🧭 Chain Scout",
      name: null,
      waiting_for: null,
      pid: 99440,
      source: "hook",
      started_at: 1_785_832_320,
      last_seen: 1_785_833_360,
    },
  ],
  work: [
    {
      id: 640,
      client: "claude",
      session_id: "7ca88f40-3aed-4f2d-be71-a80e544dd332",
      repo_root: "/Users/prb/projects/ai-coord",
      label: "monorepo-dashboard-orchestrator",
      state: "draft",
      scope_count: 3,
      draft_created_at: 1_785_833_260,
      updated_at: 1_785_833_700,
    },
    {
      id: 646,
      client: "codex",
      session_id: "019fcbf9-d75c-7ba3-a481-18068ea954eb",
      repo_root: "/Users/prb/projects/ai-coord",
      label: "dashboard-app",
      state: "active",
      scopes: [{ path: "dashboard", kind: "recursive" }],
      submitted_at: 1_785_833_606,
      updated_at: 1_785_833_718,
    },
    {
      id: 645,
      client: "codex",
      session_id: "019fcbf9-2db4-7be1-90ed-7ba4a7527a84",
      repo_root: "/Users/prb/projects/ai-coord",
      label: "serve-api",
      state: "queued",
      blocked_reason: "coverage",
      scopes: [{ path: "cli", kind: "exact" }],
      submitted_at: 1_785_833_200,
      updated_at: 1_785_833_400,
    },
    {
      id: 647,
      client: "codex",
      session_id: "019fcbf1-1a53-7e20-a682-520d66c5b87f",
      repo_root: "/Users/prb/projects/ai-coord",
      label: "docs-followup",
      state: "queued",
      blocked_reason: "held by monorepo-dashboard-orchestrator",
      scopes: [{ path: "README.md", kind: "exact" }],
      submitted_at: 1_785_833_320,
      updated_at: 1_785_833_330,
    },
    {
      id: 644,
      client: "codex",
      session_id: "019fcbc9-fc31-7772-9bc9-1c7af36775f5",
      repo_root: "/Users/prb/projects/agent-skills",
      label: "evm-atlas-routing",
      state: "active",
      scopes: [{ path: "skills/evm-atlas", kind: "recursive" }],
      submitted_at: 1_785_833_100,
      updated_at: 1_785_833_360,
    },
  ],
  handoffs: [],
  findings: [
    {
      id: "5defa09e",
      repo_root: "/Users/prb/projects/ai-coord",
      summary:
        "Provider coverage may be partial while the calling Claude session is mid-turn.",
      kind: "bug",
      state: "pending",
      paths: ["src/providers"],
      created_at: 1_785_832_989,
      updated_at: 1_785_833_705,
      terminal_at: null,
      handoff_path: null,
      commit_oid: null,
      canonical_id: null,
      sighting_count: 3,
      triaging: true,
    },
    {
      id: "4f7d2b11",
      repo_root: "/Users/prb/projects/ai-coord",
      summary:
        "Dashboard API contract is ready for the implementation handoff.",
      kind: "docs",
      state: "handed-off",
      paths: ["dashboard/src/lib/types.ts", "dashboard/src/lib/api.ts"],
      created_at: 1_785_832_600,
      updated_at: 1_785_833_000,
      terminal_at: null,
      handoff_path: "dashboard",
      commit_oid: null,
      canonical_id: null,
      sighting_count: 1,
      triaging: false,
    },
    {
      id: "5d8caf48",
      repo_root: "/Users/prb/projects/agent-skills",
      summary:
        "A terminated agent may remain visible until its provider inventory refreshes.",
      kind: "improvement",
      state: "stale",
      paths: ["skills/evm-atlas"],
      created_at: 1_785_765_099,
      updated_at: 1_785_833_360,
      terminal_at: 1_785_833_360,
      handoff_path: null,
      commit_oid: "c4b0a0e",
      canonical_id: null,
      sighting_count: 2,
      triaging: false,
    },
  ],
  delegates: [
    {
      parent_client: "claude",
      parent_session_id: "7ca88f40-3aed-4f2d-be71-a80e544dd332",
      agent_id: "a3-dashboard-implementation",
      agent_type: "codex",
      state: "active",
      last_seen: 1_785_833_722,
    },
    {
      parent_client: "claude",
      parent_session_id: "7ca88f40-3aed-4f2d-be71-a80e544dd332",
      agent_id: "a2-serve-api",
      agent_type: "codex",
      state: "active",
      last_seen: 1_785_833_710,
    },
  ],
  outside_scope: {
    sessions: 0,
    directories: 0,
  },
  messages: [
    {
      id: "b0a83f20",
      sender_client: "claude",
      sender_session_id: "7ca88f40-3aed-4f2d-be71-a80e544dd332",
      sender_callsign: "👩‍💻 Baroness Byte",
      recipient_client: "codex",
      recipient_session_id: "019fcbf9-d75c-7ba3-a481-18068ea954eb",
      recipient_callsign: "🦊 Patch Fox",
      repo_root: "/Users/prb/projects/ai-coord",
      text: "Implement dashboard/** against the approved snapshot API contract.",
      created_at: 1_785_833_720,
      acknowledged_at: null,
    },
    {
      id: "e5c9af13",
      sender_client: "codex",
      sender_session_id: "019fcbf9-2db4-7be1-90ed-7ba4a7527a84",
      sender_callsign: "🐢 Queue Kid",
      recipient_client: "claude",
      recipient_session_id: "7ca88f40-3aed-4f2d-be71-a80e544dd332",
      recipient_callsign: "👩‍💻 Baroness Byte",
      repo_root: "/Users/prb/projects/ai-coord",
      text: "The HTTP snapshot endpoint is ready for integration.",
      created_at: 1_785_833_680,
      acknowledged_at: 1_785_833_690,
    },
    {
      id: "7ba112db",
      sender_client: "codex",
      sender_session_id: "019fcbc9-fc31-7772-9bc9-1c7af36775f5",
      sender_callsign: "🧭 Chain Scout",
      recipient_client: "codex",
      recipient_session_id: "019fcbf9-d75c-7ba3-a481-18068ea954eb",
      recipient_callsign: "🦊 Patch Fox",
      repo_root: "/Users/prb/projects/agent-skills",
      text: "The provider-routing reference is the only shared generated input in this scope.",
      created_at: 1_785_833_360,
      acknowledged_at: null,
    },
  ],
  generated_at: "2026-08-04T08:15:30Z",
  generation: 646,
} satisfies Snapshot;
